# Generated by Django 2.2.3 on 2019-11-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='date_encoded',
            new_name='created_at',
        ),
    ]
